# yaml-language-server: $schema=https://coderabbit.ai/integrations/schema.v2.json
language: "ja-JP"
reviews:
  profile: "chill"
  request_changes_workflow: true
  auto_review:
    enabled: true
    base_branches:
      - main
      - develop
  path_instructions:
    - path: "src/**/*.ts"
      instructions: |
        - すべてのコードは TypeScript で記述されている必要があります。
        - 'any' 型の使用は原則禁止です。
    - path: "src/**/*.tsx"
      instructions: |
        - UIコンポーネントには 'react-native-paper' を優先的に使用しているか確認してください。
        - 命名規則は PascalCase (コンポーネント) と camelCase (関数・変数) を遵守してください。
        - モック決済ロジックにおいて、実際の金銭取引が発生しないよう安全性が保たれているか確認してください。
  ignore:
    - "node_modules/**"
    - "assets/**"
    - "*.lock"
    - ".expo/**"
