language: "ja-JP"
reviews:
  profile: "chill"
  request_changes_confirmations: true
  instructions: |
    - すべてのコードは TypeScript で記述されている必要があります。
    - 'any' 型の使用は原則禁止です。
    - UIコンポーネントには 'react-native-paper' を優先的に使用しているか確認してください。
    - 命名規則は PascalCase (コンポーネント) と camelCase (関数・変数) を遵守してください。
    - モック決済ロジックにおいて、実際の金銭取引が発生しないよう安全性が保たれているか確認してください。

path_filters:
  - "!src/**"
  - "!docs/**"
  - "node_modules/**"
  - "assets/**"
  - "*.lock"
